site_name: setting-api
site_description: Irsogy
repo_url: https://github.com/dan-source/setting-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/dan-source">dan-source</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
